services:
  # Frontend Development
  app-dev:
    build:
      context: ./web-ui
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./web-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-http://localhost:54321}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0}
    depends_on:
      supabase-db:
        condition: service_healthy

  # PostgreSQL Database
  supabase-db:
    image: postgres:15
    container_name: supabase-db
    environment:
      POSTGRES_DB: supabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./supabase/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
      - ./supabase/seed.sql:/docker-entrypoint-initdb.d/03-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: